stages:
  - stage: BuildTestAndPush
    displayName: 'Build, Test & Push'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Restoring'
            name: Restore

          - script: |
              echo 'Building'
            name: Build

          - script: |
              echo 'Testing'
            name: Test

          - script: |
              echo 'Pushing to South Africa'
              echo 'Pushing Sydney'
              echo 'Pushing America'
              echo 'Pass an array of location ids and push to those.'
            name: Push

  - stage: DeploySydneyDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Deploy to Sydney Development'
    jobs:
      - job: Plan
        displayName: 'Plan'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        dependsOn: Plan
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Installing'
                  name: Install

                - script: |
                    echo 'Initialising'
                  name: Initialise

                - script: |
                    echo 'Applying'
                  name: Apply

  - stage: DeploySydneyUAT
    displayName: 'Deploy to Sydney UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy
