# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'AWS GL'
    backendAWSBucketName: 'terraform-state-fkhj'
    backendAWSKey: 'production'
    workingDirectory: '$(Build.SourcesDirectory)/infrastructure'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'workspace'
    environmentServiceNameAWS: 'AWS GL'
    workspaceName: 'pwa'
    workspaceCreateIfNotExists: true
    workingDirectory: '$(Build.SourcesDirectory)/infrastructure'
