stages:
  - stage: BuildTestAndPush
    displayName: 'Build, Test & Push'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Restoring'
            name: Restore

          - script: |
              echo 'Building'
            name: Build

          - script: |
              echo 'Testing'
            name: Test

          - script: |
              echo 'Pushing to South Africa'
              echo 'Pushing Australia'
              echo 'Pushing America'
              echo 'Pushing New Zealand'
              echo 'Pass an array of location ids and push to those.'
            name: Push

  - stage: DeployAustraliaDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Deploy to Australia Development'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploy'
                  name: Deploy
            on:
              failure:
                steps:
                  - script: echo 'Alert Failure'
                    displayName: 'Alert Failure'
              success:
                steps:
                  - script: echo 'Alert Success'
                    displayName: 'Alert Success'

  - stage: DeployAustraliaUAT
    dependsOn: DeployAustraliaDevelopment
    displayName: 'Deploy Australia UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy

  - stage: DeploySouthAfricaDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Deploy to South Africa Development'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploy'
                  name: Deploy
            on:
              failure:
                steps:
                  - script: echo 'Alert Failure'
                    displayName: 'Alert Failure'
              success:
                steps:
                  - script: echo 'Alert Success'
                    displayName: 'Alert Success'

  - stage: DeploySouthAfricaUAT
    dependsOn: DeploySouthAfricaDevelopment
    displayName: 'Deploy South Africa UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy

  - stage: DeployAmericaDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Deploy to America Development'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploy'
                  name: Deploy
            on:
              failure:
                steps:
                  - script: echo 'Alert Failure'
                    displayName: 'Alert Failure'
              success:
                steps:
                  - script: echo 'Alert Success'
                    displayName: 'Alert Success'

  - stage: DeployAmericaUAT
    dependsOn: DeployAmericaDevelopment
    displayName: 'Deploy America UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy

  - stage: DeployNewZealandDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Deploy to New Zealand Development'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploy'
                  name: Deploy
            on:
              failure:
                steps:
                  - script: echo 'Alert Failure'
                    displayName: 'Alert Failure'
              success:
                steps:
                  - script: echo 'Alert Success'
                    displayName: 'Alert Success'

  - stage: DeployNewZealandUAT
    dependsOn: DeployNewZealandDevelopment
    displayName: 'Deploy New Zealand UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy
