stages:
  - stage: BuildTestAndPush
    displayName: 'Build, Test & Push'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Restoring'
            name: Restore

          - script: |
              echo 'Building'
            name: Build

          - script: |
              echo 'Testing'
            name: Test

          - script: |
              echo 'Pushing to South Africa'
              echo 'Pushing Australia'
              echo 'Pushing America'
              echo 'Pushing New Zealand'
              echo 'Pass an array of location ids and push to those.'
            name: Push

  - stage: PlanAustraliaDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Plan Australia Development'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

  - stage: DeployAustraliaDevelopment
    dependsOn: PlanAustraliaDevelopment
    displayName: 'Deploy to Australia Development'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploy'
                  name: Deploy
            on:
              failure:
                steps:
                  - script: echo 'Alert Failure'
                    displayName: 'Alert Failure'
              success:
                steps:
                  - script: echo 'Alert Success'
                    displayName: 'Alert Success'

  - stage: PlanAustraliaUAT
    dependsOn: DeployAustraliaDevelopment
    displayName: 'Plan Australia UAT'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

  - stage: DeployAustraliaUAT
    dependsOn: PlanAustraliaUAT
    displayName: 'Deploy Australia UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy



  - stage: PlanSouthAfricaDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Plan South Africa Development'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

  - stage: DeploySouthAfricaDevelopment
    dependsOn: PlanSouthAfricaDevelopment
    displayName: 'Deploy to South Africa Development'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploy'
                  name: Deploy
            on:
              failure:
                steps:
                  - script: echo 'Alert Failure'
                    displayName: 'Alert Failure'
              success:
                steps:
                  - script: echo 'Alert Success'
                    displayName: 'Alert Success'

  - stage: PlanSouthAfricaUAT
    dependsOn: DeploySouthAfricaDevelopment
    displayName: 'Plan South Africa UAT'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

  - stage: DeploySouthAfricaUAT
    dependsOn: PlanSouthAfricaUAT
    displayName: 'Deploy South Africa UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy




  - stage: PlanAmericaDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Plan America Development'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

  - stage: DeployAmericaDevelopment
    dependsOn: PlanAmericaDevelopment
    displayName: 'Deploy to America Development'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploy'
                  name: Deploy
            on:
              failure:
                steps:
                  - script: echo 'Alert Failure'
                    displayName: 'Alert Failure'
              success:
                steps:
                  - script: echo 'Alert Success'
                    displayName: 'Alert Success'

  - stage: PlanAmericaUAT
    dependsOn: DeployAmericaDevelopment
    displayName: 'Plan America UAT'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

  - stage: DeployAmericaUAT
    dependsOn: PlanAmericaUAT
    displayName: 'Deploy America UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy




  - stage: PlanNewZealandDevelopment
    dependsOn: BuildTestAndPush
    displayName: 'Plan New Zealand Development'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

  - stage: DeployNewZealandDevelopment
    dependsOn: PlanNewZealandDevelopment
    displayName: 'Deploy to New Zealand Development'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploy'
                  name: Deploy
            on:
              failure:
                steps:
                  - script: echo 'Alert Failure'
                    displayName: 'Alert Failure'
              success:
                steps:
                  - script: echo 'Alert Success'
                    displayName: 'Alert Success'

  - stage: PlanNewZealandUAT
    dependsOn: DeployNewZealandDevelopment
    displayName: 'Plan New Zealand UAT'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo 'Installing'
            name: Install

          - script: |
              echo 'Initialising'
            name: Initialise

          - script: |
              echo 'Planning'
            name: Plan

  - stage: DeployNewZealandUAT
    dependsOn: PlanNewZealandUAT
    displayName: 'Deploy New Zealand UAT'
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo 'Deploying'
                  name: Deploy
